import Footer from './Components/Base/Footer'
import Header from './Components/Base/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative">
      <div className=''>
      <Header/>
      </div>
      <div className=''>
      {children}
      </div>
      <div className=''>
      <Footer/>
      </div>
      </body>
    </html>
  )
}
